name: Feature Request
description: Suggest a new feature or enhancement for biometal
title: "[Feature]: "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature for biometal! Please provide details about your use case and the proposed solution.

  - type: textarea
    id: problem
    attributes:
      label: Problem or Use Case
      description: What problem does this feature solve? What use case does it enable?
      placeholder: |
        Example: I need to parse CRAM files for my WGS analysis pipeline, but biometal currently only supports BAM/SAM formats.
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this feature to work? Provide API examples if possible.
      placeholder: |
        ```python
        import biometal

        # Proposed API
        reader = biometal.CramReader.from_path("alignments.cram", reference="hg38.fa")
        for record in reader:
            process(record)
        ```
      render: python
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What workarounds or alternative solutions have you considered?
      placeholder: |
        Example: Currently using samtools to convert CRAM to BAM, but this requires extra disk space and processing time.

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to your workflow?
      options:
        - Critical - Blocking my work
        - High - Would significantly improve my workflow
        - Medium - Nice to have
        - Low - Small quality-of-life improvement
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: What category does this feature belong to?
      options:
        - File format support (CRAM, VCF, BCF, etc.)
        - Performance optimization
        - API enhancement
        - Python bindings
        - Documentation
        - Network streaming
        - Index support (CSI, TBI, etc.)
        - Quality of life improvement
        - Other
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any additional information that might be helpful
      placeholder: |
        - Links to format specifications
        - Example datasets
        - Performance requirements
        - Related work in other tools

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you be interested in contributing to this feature?
      options:
        - label: I would be willing to implement this feature with guidance
        - label: I would be willing to test this feature
        - label: I can provide sample data or benchmarks

  - type: checkboxes
    id: search
    attributes:
      label: Pre-submission Checklist
      description: Please confirm you've completed these steps before submitting
      options:
        - label: I have searched existing issues and discussions to avoid duplicates
          required: true
        - label: I have described a clear use case for this feature
          required: true
